FROM node:14
WORKDIR /app
EXPOSE 8080

# If package.json is not changed, this line should have caching.
COPY package.json /app/package.json
RUN npm install
# Copying codes in the end is to improve caching.
COPY . .
CMD ["npm", "run", "serve"]