# Development docker compose.

version: "3"
services:

  # Make sure that production db is working. Other wise, uncomment these lines.

  # db:
  #   container_name: ${CONTAINER_DB}
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - sklec_vis_db:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  server:
    container_name: ${CONTAINER_SERVER}
    build:
      context: ./server
      dockerfile: Dockerfile
    command: docker/django-start-dev.sh
    environment:
      DJANGO_SETTINGS_MODULE: sklecvis.settings
      DB_HOST: 172.20.5.126 # For local debugging
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: sklecvis
      PYTHONPATH: /app
    expose:
      - "8000"
    volumes:
      - ./server:/app
      # 如果使用生产环境 media：
      - /srv/sklec-vis/server/media:/app/media

      # 监听文件夹
      - /home/public/sklecvis-autoupload:/data/autoupload


  client:
    container_name: ${CONTAINER_CLIENT}
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public

  nginx:
    container_name: ${CONTAINER_NGINX}
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    ports:
      - "${DEV_PORT}:80"
    volumes:
      - ./server/static/:/srv/server_static
      # 如果使用开发自己 media：
      # - ./server/media/:/srv/server_media

      # 如果使用生产环境 media：
      - /srv/sklec-vis/server/media:/srv/server_media # media file of production environment.
    depends_on:
      - server
      - client

volumes:
  sklec_vis_db: {}