# Development docker compose.

version: "3"
services:

  db:
    container_name: sklecvis-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: sklecVIS2022
    volumes:
      - sklec_vis_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: sklecvis-server
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    environment:
      DJANGO_SETTINGS_MODULE: sklecvis.settings
      DB_HOST: sklecvis-db # For local debugging
#       DB_HOST: aws-jp.billc.io          # To maintain the consistence of the database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: sklecVIS2022
      DB_NAME: sklecvis
      PYTHONPATH: /app
    expose:
      - "8000"
    volumes:
      - ./server:/app

  client:
    container_name: sklecvis-client
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - ./client:/app

  nginx:
    container_name: sklecvis-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    ports:
      - "8060:80"
    volumes:
      - ./server/static/:/srv/server_static
      - ./server/media/:/srv/server_media
    depends_on:
      - server
      - client

volumes:
  sklec_vis_db: {}