# Generated by Django 4.0.2 on 2022-03-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rawfile_visfile_alter_dataset_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visfile',
            name='bounds_leftup',
        ),
        migrations.RemoveField(
            model_name='visfile',
            name='bounds_rightdown',
        ),
        migrations.AddField(
            model_name='dataset',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='file_same_as_vis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='visfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visfile'),
        ),
        migrations.AddField(
            model_name='visfile',
            name='default_sample_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visfile',
            name='format',
            field=models.CharField(choices=[('rsk', 'Rsk'), ('csv', 'Csv'), ('tiff', 'Tiff'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='visfile',
            name='georeinforced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visfile',
            name='latitude1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visfile',
            name='latitude2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visfile',
            name='longitude1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visfile',
            name='longitude2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(choices=[('RBR', 'Rbr'), ('NCF', 'Ncf'), ('RT', 'Raster'), ('TABLE', 'Table'), ('GNR', 'General')], default='GNR', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='datasets/raw/'),
        ),
        migrations.AlterField(
            model_name='visfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='datasets/vis/'),
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_datetime', models.DateTimeField(auto_now_add=True)),
                ('login_ip', models.GenericIPAddressField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_datetime', models.DateTimeField(auto_now_add=True)),
                ('download_ip', models.GenericIPAddressField()),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dataset')),
                ('rawfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rawfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='DataChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime_start', models.DateTimeField(blank=True, null=True)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('visfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.visfile')),
            ],
        ),
    ]
