# Generated by Django 4.0.2 on 2022-03-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_visfile_bounds_leftup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginrecord',
            old_name='login_ip',
            new_name='ip',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PasswordUpdateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('previous_password', models.CharField(max_length=200)),
                ('new_password', models.CharField(max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.siteuser')),
            ],
        ),
    ]
