# Generated by Django 4.0.2 on 2022-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_datasettag_datachannel_is_xaxis_alter_visfile_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datachannel',
            name='is_xaxis',
        ),
        migrations.AddField(
            model_name='visfile',
            name='first_dimension_name',
            field=models.CharField(blank=True, default='Time', max_length=50, null=True),
        ),
    ]
