# Generated by Django 4.0.2 on 2022-04-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_visfile_georeference_type_alter_dataset_meta_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visfile',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visfile',
            name='datetime_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visfile',
            name='georeference_type',
            field=models.CharField(choices=[('geotiff', 'Geotiff'), ('explicit', 'Explicit'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
