# Generated by Django 3.2.12 on 2022-04-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_visfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datachannel',
            name='add_offset',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='datachannel',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='datachannel',
            name='missing_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='datachannel',
            name='scale_factor',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
