# Generated by Django 4.0.2 on 2022-05-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_visfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datachannel',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
