# Generated by Django 3.2.12 on 2022-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220407_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='datachannel',
            name='channel_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datachannel',
            name='add_offset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datachannel',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datachannel',
            name='missing_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datachannel',
            name='scale_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
