# Generated by Django 4.0.2 on 2022-05-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_datachannel_meta_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasettag',
            old_name='long_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='datasettag',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datasettag'),
        ),
    ]
