# Generated by Django 4.0.2 on 2022-05-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_long_name_datasettag_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datasettag'),
        ),
    ]
