# Generated by Django 4.0.2 on 2022-07-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_datasettag_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTiffFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preview', models.BooleanField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('longitude_start', models.IntegerField(blank=True, null=True)),
                ('longitude_end', models.IntegerField(blank=True, null=True)),
                ('latitude_start', models.IntegerField(blank=True, null=True)),
                ('latitude_end', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('file', models.CharField(blank=True, max_length=256, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('last_access_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
