# Generated by Django 4.0.2 on 2022-07-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_siteuser_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
