# Generated by Django 4.0.2 on 2022-09-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_rawfile_dataset_alter_visfile_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='visfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.visfile'),
        ),
    ]
