# Generated by Django 4.0.2 on 2022-09-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_rawfile_visfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viewtifffile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visfile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
