# Generated by Django 4.0.2 on 2022-10-25 12:11

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_rawfile_file_size_alter_viewtifffile_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDataFieldMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=api.models.uuid4_short, editable=False, max_length=20)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('attribute_type', models.CharField(choices=[('default', 'Default'), ('numerical', 'Numerical'), ('temporal', 'Temporal'), ('spacial', 'Spacial'), ('categorical', 'Categorical')], default='default', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('index', models.IntegerField(blank=True, default=0, null=True)),
                ('meta_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FormDataTableMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=api.models.uuid4_short, editable=False, max_length=20)),
                ('type', models.CharField(choices=[('benthos', 'Benthos'), ('surface_sediment', 'Surface Sediment'), ('vegetation', 'Vegetation'), ('default', 'Default')], default='default', max_length=20)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.DatasetTag'),
        ),
        migrations.CreateModel(
            name='FormDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=api.models.uuid4_short, editable=False, max_length=20)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('meta_data', models.JSONField(default=dict)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.dataset')),
                ('table_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.formdatatablemeta')),
            ],
        ),
        migrations.CreateModel(
            name='FormDataFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=api.models.uuid4_short, editable=False, max_length=20)),
                ('index_row', models.IntegerField(blank=True, null=True)),
                ('value_numerical', models.FloatField(blank=True, null=True)),
                ('value_temporal', models.DateTimeField(blank=True, null=True)),
                ('value_spacial', models.FloatField(blank=True, null=True)),
                ('value_categorical', models.CharField(blank=True, max_length=256, null=True)),
                ('field_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='api.formdatafieldmeta')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='api.formdatatable')),
            ],
        ),
        migrations.AddField(
            model_name='formdatafieldmeta',
            name='table_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_types', to='api.formdatatablemeta'),
        ),
    ]
