# Generated by Django 4.0.2 on 2022-11-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_formdatafieldmeta_formdatatablemeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visfile',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafieldvalue',
            name='index_row',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafieldvalue',
            name='value_categorical',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafieldvalue',
            name='value_numerical',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafieldvalue',
            name='value_spacial',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafieldvalue',
            name='value_temporal',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
