# Generated by Django 4.0.2 on 2022-10-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_formdatafieldtype_formdatatabletype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdatatabletype',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafieldtype',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafieldtype',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
