# Generated by Django 4.0.2 on 2022-10-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_formdatatabletype_name_alter_formdatafieldtype_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdatafieldvalue',
            name='value_spacial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafieldvalue',
            name='value_temporal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
