# Generated by Django 4.0.2 on 2022-11-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_visfile_info_alter_formdatafieldvalue_index_row_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdatafieldvalue',
            old_name='field_type',
            new_name='field_meta',
        ),
        migrations.RenameField(
            model_name='formdatatable',
            old_name='table_type',
            new_name='table_meta',
        ),
        migrations.RemoveField(
            model_name='formdatafieldmeta',
            name='table_type',
        ),
        migrations.AddField(
            model_name='formdatafieldmeta',
            name='table_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_metas', to='api.formdatatablemeta'),
        ),
    ]
