# Generated by Django 4.0.2 on 2022-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_field_type_formdatafieldvalue_field_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdatafieldmeta',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafieldvalue',
            name='index_row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
