# Generated by Django 4.0.2 on 2022-11-07 12:05

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_formdatafieldmeta_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDataCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=api.models.uuid4_short, editable=False, max_length=20)),
                ('index_row', models.IntegerField(blank=True, default=0, null=True)),
                ('value_numerical', models.FloatField(blank=True, default=None, null=True)),
                ('value_temporal', models.DateTimeField(blank=True, default=None, null=True)),
                ('value_spacial', models.FloatField(blank=True, default=None, null=True)),
                ('value_categorical', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='formdatafieldmeta',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='FormDataFieldValue',
        ),
        migrations.AddField(
            model_name='formdatacell',
            name='field_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='api.formdatafieldmeta'),
        ),
        migrations.AddField(
            model_name='formdatacell',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='api.formdatatable'),
        ),
    ]
