# Generated by Django 4.0.2 on 2022-11-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_formdatacell_alter_formdatafieldmeta_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdatacell',
            name='field_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='api.formdatafieldmeta'),
        ),
        migrations.AlterField(
            model_name='formdatacell',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='api.formdatatable'),
        ),
    ]
