# Generated by Django 4.0.2 on 2022-11-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_formdatacell_field_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdatacell',
            name='value_default',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
