FROM python:3.9-alpine
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
EXPOSE 3000
ADD ./requirements.txt /app/requirements.txt
RUN apk add --no-cache gcc libc-dev linux-headers musl-dev
RUN apk add python3-dev py3-numpy jpeg-dev zlib-dev g++ # For Pillow and numpy
# RUN apk add hdf5 netcdf
RUN apk add hdf5-dev netcdf-dev
RUN apk add --no-cache --virtual .build-deps postgresql-dev gdal gdal-dev 
RUN pip config set global.index-url https://pypi.douban.com/simple/
RUN pip install uwsgi
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
RUN pip uninstall gdal -y && pip install gdal

RUN pip install ipython # for debugging

COPY . .
RUN python manage.py collectstatic --noinput

CMD ["uwsgi", "--ini", "uwsgi.ini", \
    "--py-autoreload", "1", \
    "--socket", ":3000", \
    "--plugins", "python3"]
