name: AWS Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: AWS Env
      run: |
        eval $(ssh-agent -s)
        echo "${{secrets.AWS_PRIVATE_KEY}}" > key.pem
        chmod 600 key.pem
        mkdir ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - name: AWS Deploy
      run: |
        ssh -i key.pem ${{secrets.AWS_SERVER_USERNAME}}@${{secrets.AWS_SERVER_IP}} "cd ~/sklec-vis && git pull && sudo ./bin/production.sh --start"
